apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/bbq-bean/argo-cd-example.git
    targetRevision: main
    path: app1-example/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

